name: Deploy to Arweave

on:
  workflow_run:
    workflows: ["Build"]
    branches:  [main]               # deploy only when CI on main passed
    types:    [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
      
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci --prefer-offline --no-audit

      - name: Deploy to Arweave
        run: npm run deploy
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_ANT_PROCESS_ID: ${{ secrets.DEPLOY_ANT_PROCESS_ID }}
          DEPLOY_UNDERNAME: ${{ secrets.DEPLOY_UNDERNAME }}
        run: |
          if [ -z "$DEPLOY_UNDERNAME" ]; then
            echo "Error: DEPLOY_UNDERNAME secret is required but not set"
            echo "Please set the DEPLOY_UNDERNAME secret in your repository settings"
            echo "If you want to deploy without an undername, use the alternative configuration below"
            exit 1
          fi
          echo "Deploying with undername: $DEPLOY_UNDERNAME"
          npm run deploy-undername

      # Alternative deployment configuration (commented out):
      # Use this if you want to deploy directly to the base ArNS without an undername
      # To use this, comment out the above "Deploy with undername" step and uncomment this one
      #- name: Deploy without undername
      #  env:
      #    DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      #    DEPLOY_ANT_PROCESS_ID: ${{ secrets.DEPLOY_ANT_PROCESS_ID }}
      #  run: |
      #    echo "Deploying without undername to base ArNS"
      #    npm run deploy
